### ISSUE TITLE
Suffix added to download url is incorrect in version 2.0.1

### ISSUE THREAD

**Issue by bearrito** [evenup/evenup-kibana#28]
When setting the version it appears that the constructed url is improperly suffixed with '-linux-x86'
   ```
wget --no-verbose --output-document='/tmp/kibana-3.1.0-linux-x64.tar.gz' 'https://download.elasticsearch.org/kibana/kibana/kibana-3.1.0-linux-x64.tar.gz' returned 8 instead of one of [0]

```
The download links differ between the versions. 

    https://download.elastic.co/kibana/kibana/kibana-4.0.2-linux-x86.tar.gz

    https://download.elastic.co/kibana/kibana/kibana-3.1.0.tar.gz

**Comment by jlambert121** [comment]
The difference is because kibana >= 4 is a binary distribution providing a nodejs server along with the web component.  3 >= Kibana < 4 is a webapp only providing html/css/js files.  The older version of this module supported kibana 3, this version only supports version 4.  I should probably document that better.

**Comment by bearrito** [comment]
Thats helpful to know. I couldn't use the older version because it didn't allow me to specify a base_url to download from. I ended up with just using the archive module.

**Comment by jlambert121** [comment]
When you go to the 4.0 series hopefully this will be more useful.
